#Database
POSTGRES_USERNAME: ${ENV_POSTGRES_USERNAME}
POSTGRES_PASSWORD: ${ENV_POSTGRES_PASSWORD}
POSTGRES_HOST: localhost
POSTGRES_PORT: 5432
POSTGRES_DATABASE: hotel_db
TEST_POSTGRES_DATABASE: hotel_test_db


#Server
ACTIVE_PROFILE: dev
